version: "3.12"

services:
  api: &case_api
    container_name: civil_case_api
    build: .
    ports:
      - "8027:8027"
    restart: "no"
    volumes:
      - ".:/case_api"
    environment:
      - CLA_ENVIRONMENT=${CLA_ENVIRONMENT:-}