{
 "title": "LAA Civil Case API",
 "time": { "from": "now-30d", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "namespace",
    "label": "Namespace",
    "query": "label_values(kube_deployment_metadata_generation, namespace)"
   },
   {
    "name": "ingress",
    "query": {
     "query": "label_values(nginx_ingress_controller_requests{exported_namespace=\"$namespace\"},ingress)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Civil Case API", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Pod Info",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 9, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kube_pod_container_info{namespace='$namespace'})",
     "legendFormat": "Total"
    },
    {
     "expr": "sum({namespace='$namespace' ,phase='Running'} + 0)",
     "legendFormat": "Running"
    },
    {
     "expr": "sum({namespace='$namespace',phase='Pending'} + 0)",
     "legendFormat": "Pending"
    },
    {
     "expr": "sum({namespace='$namespace',phase='Failed'} + 0)",
     "legendFormat": "Failed"
    }
   ]
  },
  {
   "title": "HTTP Request Rate",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 15, "x": 9, "y": 1 },
   "targets": [
    {
     "expr": "sum(rate(http_requests_total{namespace='$namespace'}[1m])) by (status)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Database Connections",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 9, "x": 0, "y": 7 },
   "targets": [
    {
     "dimensions": {
      "DBInstanceIdentifier": "cloud-platform-ea49bfb7f8392895"
     },
     "label": "UAT",
     "metricName": "DatabaseConnections",
     "namespace": "AWS/RDS",
     "queryMode": "Metrics",
     "region": "default",
     "statistic": "Average"
    },
    {
     "dimensions": {
      "DBInstanceIdentifier": "cloud-platform-0838e5e50d1b17da"
     },
     "label": "Dev",
     "metricName": "DatabaseConnections",
     "namespace": "AWS/RDS",
     "queryMode": "Metrics",
     "region": "default",
     "statistic": "Average"
    },
    {
     "dimensions": {
      "DBInstanceIdentifier": "cloud-platform-10f3c2233e2da81a"
     },
     "label": "Staging",
     "metricName": "DatabaseConnections",
     "namespace": "AWS/RDS",
     "queryMode": "Metrics",
     "region": "default",
     "statistic": "Average"
    },
    {
     "dimensions": {
      "DBInstanceIdentifier": "cloud-platform-960617ea387b8ac4"
     },
     "label": "Production",
     "metricName": "DatabaseConnections",
     "namespace": "AWS/RDS",
     "queryMode": "Metrics",
     "region": "default",
     "statistic": "Average"
    }
   ]
  },
  {
   "title": "RDS CPU Credit Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 15, "x": 9, "y": 7 },
   "targets": [
    {
     "dimensions": {
      "DBInstanceIdentifier": "cloud-platform-960617ea387b8ac4"
     },
     "label": "Prod",
     "metricName": "CPUCreditUsage",
     "namespace": "AWS/RDS",
     "queryMode": "Metrics",
     "region": "default",
     "statistic": "Average"
    },
    {
     "dimensions": {
      "DBInstanceIdentifier": "cloud-platform-10f3c2233e2da81a"
     },
     "label": "Staging",
     "metricName": "CPUCreditUsage",
     "namespace": "AWS/RDS",
     "queryMode": "Metrics",
     "region": "default",
     "statistic": "Average"
    },
    {
     "dimensions": {
      "DBInstanceIdentifier": "cloud-platform-0838e5e50d1b17da"
     },
     "label": "Dev",
     "metricName": "CPUCreditUsage",
     "namespace": "AWS/RDS",
     "queryMode": "Metrics",
     "region": "default",
     "statistic": "Average"
    },
    {
     "dimensions": {
      "DBInstanceIdentifier": "cloud-platform-ea49bfb7f8392895"
     },
     "label": "UAT",
     "metricName": "CPUCreditUsage",
     "namespace": "AWS/RDS",
     "queryMode": "Metrics",
     "region": "default",
     "statistic": "Average"
    }
   ]
  },
  {
   "title": "Container Restarts",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 15 },
   "targets": [
    {
     "expr": "kube_pod_container_status_restarts_total{namespace=\"$namespace\"}",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Ingress Requests",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 23 },
   "targets": [
    {
     "expr": "sum(rate(nginx_ingress_controller_request_duration_seconds_count{exported_namespace = \"$namespace\", path !~\"/socket.io/.*\", ingress = \"$ingress\"}[5m]))",
     "legendFormat": "req / m"
    }
   ]
  },
  {
   "title": "Memory usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 31 },
   "targets": [
    {
     "expr": "sum by(pod_name)(container_memory_usage_bytes{namespace='$namespace'})",
     "legendFormat": "POD: {{ pod_name}}"
    },
    {
     "expr": "avg(kube_pod_container_resource_requests_memory_bytes{namespace='$namespace'})",
     "legendFormat": "Requested (soft limit)"
    },
    {
     "expr": "avg(kube_pod_container_resource_limits_memory_bytes{namespace='$namespace'})",
     "legendFormat": "Limit (hard limit)"
    }
   ]
  },
  {
   "title": "CPU usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 39 },
   "targets": [
    {
     "expr": "sum by (pod_name)(rate(container_cpu_usage_seconds_total{namespace='$namespace'}[5m]))",
     "legendFormat": "POD: {{ pod_name}}"
    },
    {
     "expr": "avg(kube_pod_container_resource_requests_cpu_cores{namespace='$namespace'})",
     "legendFormat": "Requested (soft limit)"
    },
    {
     "expr": "avg(kube_pod_container_resource_limits_cpu_cores{namespace='$namespace'})",
     "legendFormat": "Limit (hard limit)"
    }
   ]
  },
  {
   "title": "Network",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 47 },
   "targets": [
    {
     "expr": "sort_desc(avg(sum by (pod_name) (rate(container_network_receive_bytes_total{namespace='$namespace'}[5m]))))",
     "legendFormat": "Recv"
    },
    {
     "expr": "sort_desc(avg(sum by (pod_name) (rate(container_network_transmit_bytes_total{namespace='$namespace'}[5m]))))",
     "legendFormat": "Sent"
    }
   ]
  }
 ]
}