"""case adaptations

Revision ID: c4b9d0057513
Revises: 117a6ec2770b
Create Date: 2024-11-11 14:37:55.834314

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from alembic_postgresql_enum import TableReference

# revision identifiers, used by Alembic.
revision: str = "c4b9d0057513"
down_revision: Union[str, None] = "117a6ec2770b"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "case_adaptations",
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("needed_adaptations", sa.JSON(), nullable=True),
        sa.Column("languages", sa.JSON(), nullable=True),
        sa.Column("case_id", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(
            ["case_id"],
            ["cases.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_case_adaptations_case_id"),
        "case_adaptations",
        ["case_id"],
        unique=False,
    )
    op.sync_enum_values(
        "public",
        "notetype",
        ["adaptation", "personal", "provider", "caseworker", "operator", "other"],
        [
            TableReference(
                table_schema="public", table_name="case_notes", column_name="note_type"
            )
        ],
        enum_values_to_rename=[],
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.sync_enum_values(
        "public",
        "notetype",
        ["personal", "provider", "caseworker", "operator", "other"],
        [
            TableReference(
                table_schema="public", table_name="case_notes", column_name="note_type"
            )
        ],
        enum_values_to_rename=[],
    )
    op.drop_index(op.f("ix_case_adaptations_case_id"), table_name="case_adaptations")
    op.drop_table("case_adaptations")
    # ### end Alembic commands ###
