"""user scopes

Revision ID: d4223a91f1de
Revises: c4b9d0057513
Create Date: 2024-11-21 11:33:22.255372

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "d4223a91f1de"
down_revision: Union[str, None] = "c4b9d0057513"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("users", sa.Column("scopes", sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("users", "scopes")
    # ### end Alembic commands ###
