# Default values for laa-civil-case-api.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicas:
  app: 1
  worker: 1
environment: development
image:
  repository: laa-civil-case-api
  pullPolicy: IfNotPresent
  containerPort: 8027
  # Overrides the image tag whose default is the chart appVersion.
  tag: ""

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

serviceAccount:
  create: false

podAnnotations: {}
podLabels: {}

podSecurityContext: {}

securityContext:
  runAsNonRoot: true
  runAsUser: 1000
  allowPrivilegeEscalation: false
  seccompProfile:
    type: RuntimeDefault
  capabilities:
    drop: ["ALL"]

service:
  type: ClusterIP
  port: 80

ingress:
  enabled: true
  className: "default"
  annotations: {}
  cluster:
    name: green
    weight: '100'
  tls: []

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80
  # targetMemoryUtilizationPercentage: 80

envVars:
  SENTRY_DSN:
    secret:
      name: sentry
      key: dsn
  SECRET_KEY:
    secret:
      name: secretkey
      key: value
  DB_NAME:
    secret:
      name: rds-postgresql-instance-output
      key: database_name
  DB_USER:
    secret:
      name: rds-postgresql-instance-output
      key: database_username
  DB_PASSWORD:
    secret:
      name: rds-postgresql-instance-output
      key: database_password
  DB_HOST:
    secret:
      name: rds-postgresql-instance-output
      key: rds_instance_address
  DB_PORT:
    value: 5432
  
