# Default values for laa-civil-case-api.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicas:
  app: 1
  worker: 1
environment: development
image:
  repository: laa-civil-case-api
  pullPolicy: IfNotPresent
  containerPort: 8026
  # Overrides the image tag whose default is the chart appVersion.
  tag: ""

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

serviceAccount:
  create: false

podAnnotations: {}
podLabels: {}

podSecurityContext: {}

securityContext:
  runAsNonRoot: true
  runAsUser: 1000
  allowPrivilegeEscalation: false
  seccompProfile:
    type: RuntimeDefault
  capabilities:
    drop: ["ALL"]

service:
  type: ClusterIP
  port: 80

ingress:
  enabled: false
  className: "default"
  annotations: {}
  cluster:
    name: green
    weight: '100'
  tls: []
  whitelist:
    # GlobalProtect VPN (Digital Mac)
    - 18.169.147.172/32
    - 35.176.93.186/32
    - 18.130.148.126/32
    - 35.176.148.126/32

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80
  # targetMemoryUtilizationPercentage: 80